'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Web.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("IPSNorte.Portal.Web.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset Password.
        '''</summary>
        Public ReadOnly Property AccountController_ForgotPassword_Reset_Password() As String
            Get
                Return ResourceManager.GetString("AccountController_ForgotPassword_Reset_Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid username or password..
        '''</summary>
        Public ReadOnly Property AccountController_Login_Invalid_username_or_password_() As String
            Get
                Return ResourceManager.GetString("AccountController_Login_Invalid_username_or_password_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please reset your password by clicking &lt;a href=&quot;.
        '''</summary>
        Public ReadOnly Property AccountController_ResetPassword() As String
            Get
                Return ResourceManager.GetString("AccountController_ResetPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;&gt;here&lt;/a&gt;.
        '''</summary>
        Public ReadOnly Property AccountController_RestPassword2() As String
            Get
                Return ResourceManager.GetString("AccountController_RestPassword2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IPSNorte - Ticketing Portal.
        '''</summary>
        Public ReadOnly Property ApplicationName() As String
            Get
                Return ResourceManager.GetString("ApplicationName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I accept.
        '''</summary>
        Public ReadOnly Property CookieWarningView_Accept() As String
            Get
                Return ResourceManager.GetString("CookieWarningView_Accept", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This application uses cookies, both own and third party&apos;s. You can read our {0}. By continuing we consider you accept it&apos;s usage..
        '''</summary>
        Public ReadOnly Property CookieWarningView_Message() As String
            Get
                Return ResourceManager.GetString("CookieWarningView_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to privacy policy.
        '''</summary>
        Public ReadOnly Property CookieWarningView_PrivacyPolicy() As String
            Get
                Return ResourceManager.GetString("CookieWarningView_PrivacyPolicy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create Ticket.
        '''</summary>
        Public ReadOnly Property CreateTicketView_CreateTicket() As String
            Get
                Return ResourceManager.GetString("CreateTicketView_CreateTicket", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upload File.
        '''</summary>
        Public ReadOnly Property CreateTicketView_UploadFile() As String
            Get
                Return ResourceManager.GetString("CreateTicketView_UploadFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date is required.
        '''</summary>
        Public ReadOnly Property CreateTicketViewModel_CreatedDate_Date_is_required() As String
            Get
                Return ResourceManager.GetString("CreateTicketViewModel_CreatedDate_Date_is_required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description is required.
        '''</summary>
        Public ReadOnly Property CreateTicketViewModel_Description_Description_is_required() As String
            Get
                Return ResourceManager.GetString("CreateTicketViewModel_Description_Description_is_required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number is required.
        '''</summary>
        Public ReadOnly Property CreateTicketViewModel_Number_Number_is_required() As String
            Get
                Return ResourceManager.GetString("CreateTicketViewModel_Number_Number_is_required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Priority.
        '''</summary>
        Public ReadOnly Property CreateTicketViewModel_Priority() As String
            Get
                Return ResourceManager.GetString("CreateTicketViewModel_Priority", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Project Number.
        '''</summary>
        Public ReadOnly Property CreateTicketViewModel_ProjectNumber() As String
            Get
                Return ResourceManager.GetString("CreateTicketViewModel_ProjectNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Project Number is required.
        '''</summary>
        Public ReadOnly Property CreateTicketViewModel_ProjectNumber_Project_Number_is_required() As String
            Get
                Return ResourceManager.GetString("CreateTicketViewModel_ProjectNumber_Project_Number_is_required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File description.
        '''</summary>
        Public ReadOnly Property FileDescription() As String
            Get
                Return ResourceManager.GetString("FileDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File name.
        '''</summary>
        Public ReadOnly Property FileName() As String
            Get
                Return ResourceManager.GetString("FileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File size.
        '''</summary>
        Public ReadOnly Property FileSize() As String
            Get
                Return ResourceManager.GetString("FileSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome to the IPS Ticketing Portal, here you will be able to see progress of open tickets, report issues and see blah... blah....
        '''</summary>
        Public ReadOnly Property IndexPage_Intro() As String
            Get
                Return ResourceManager.GetString("IndexPage_Intro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Us.
        '''</summary>
        Public ReadOnly Property LoginView_Contact() As String
            Get
                Return ResourceManager.GetString("LoginView_Contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Public ReadOnly Property LoginView_Login() As String
            Get
                Return ResourceManager.GetString("LoginView_Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Register.
        '''</summary>
        Public ReadOnly Property LoginView_Register() As String
            Get
                Return ResourceManager.GetString("LoginView_Register", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remember me?.
        '''</summary>
        Public ReadOnly Property LoginViewModel_RememberMe_Remember_me_() As String
            Get
                Return ResourceManager.GetString("LoginViewModel_RememberMe_Remember_me_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm new password.
        '''</summary>
        Public ReadOnly Property ManageUserViewModel_ConfirmPassword_Confirm_new_password() As String
            Get
                Return ResourceManager.GetString("ManageUserViewModel_ConfirmPassword_Confirm_new_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The new password and confirmation password do not match..
        '''</summary>
        Public ReadOnly Property ManageUserViewModel_ConfirmPassword_The_new_password_and_confirmation_password_do_not_match_() As String
            Get
                Return ResourceManager.GetString("ManageUserViewModel_ConfirmPassword_The_new_password_and_confirmation_password_do"& _ 
                        "_not_match_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New password.
        '''</summary>
        Public ReadOnly Property ManageUserViewModel_NewPassword_New_password() As String
            Get
                Return ResourceManager.GetString("ManageUserViewModel_NewPassword_New_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current password.
        '''</summary>
        Public ReadOnly Property ManageUserViewModel_OldPassword_Current_password() As String
            Get
                Return ResourceManager.GetString("ManageUserViewModel_OldPassword_Current_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ticket Details.
        '''</summary>
        Public ReadOnly Property PageTitle_TicketDetails() As String
            Get
                Return ResourceManager.GetString("PageTitle_TicketDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tickets.
        '''</summary>
        Public ReadOnly Property PageTitle_TicketsIndex() As String
            Get
                Return ResourceManager.GetString("PageTitle_TicketsIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company.
        '''</summary>
        Public ReadOnly Property RegisterViewModel_Company_Company() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_Company_Company", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm password.
        '''</summary>
        Public ReadOnly Property RegisterViewModel_ConfirmPassword_Confirm_password() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_ConfirmPassword_Confirm_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The password and confirmation password do not match..
        '''</summary>
        Public ReadOnly Property RegisterViewModel_ConfirmPassword_The_password_and_confirmation_password_do_not_match_() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_ConfirmPassword_The_password_and_confirmation_password_do_not_m"& _ 
                        "atch_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Public ReadOnly Property RegisterViewModel_Email_Email() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_Email_Email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Name.
        '''</summary>
        Public ReadOnly Property RegisterViewModel_FirstName_First_Name() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_FirstName_First_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job role.
        '''</summary>
        Public ReadOnly Property RegisterViewModel_JobRole_Job_role() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_JobRole_Job_role", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Name.
        '''</summary>
        Public ReadOnly Property RegisterViewModel_LastName_Last_Name() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_LastName_Last_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Public ReadOnly Property RegisterViewModel_Password_Password() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_Password_Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The {0} must be at least {2} characters long..
        '''</summary>
        Public ReadOnly Property RegisterViewModel_Password_The__0__must_be_at_least__2__characters_long_() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_Password_The__0__must_be_at_least__2__characters_long_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone number.
        '''</summary>
        Public ReadOnly Property RegisterViewModel_Phone1_Phone_number() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_Phone1_Phone_number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile phone number.
        '''</summary>
        Public ReadOnly Property RegisterViewModel_Phone2_Mobile_phone_number() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_Phone2_Mobile_phone_number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Project number.
        '''</summary>
        Public ReadOnly Property RegisterViewModel_ProjectNumber_Project_number() As String
            Get
                Return ResourceManager.GetString("RegisterViewModel_ProjectNumber_Project_number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the characters below.
        '''</summary>
        Public ReadOnly Property RegiterPage_CaptchaInputText() As String
            Get
                Return ResourceManager.GetString("RegiterPage_CaptchaInputText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh text.
        '''</summary>
        Public ReadOnly Property RegiterPage_CaptchaRefreshText() As String
            Get
                Return ResourceManager.GetString("RegiterPage_CaptchaRefreshText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter the characters as shown.
        '''</summary>
        Public ReadOnly Property RegiterPage_CaptchaRequiredText() As String
            Get
                Return ResourceManager.GetString("RegiterPage_CaptchaRequiredText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
